= C1DN -  COVID-19 Updated


== *C1DN -  COVID-19 Updated*


=== `COMPOSITION: _openEHR-EHR-COMPOSITION.report.v1_`


===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|====
=== context
===== `EVENT_CONTEXT: _`RM:context`_`
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0002 + 
 `report_id`| 0..1| DV_TEXT | Report ID
a|


Identification information about the report.
|at0005 + 
 `status`| 0..1| DV_TEXT | Status
a|


The status of the entire report. Note: This is not the status of any of the report components.
|====
=== Provider
===== `ADMIN_ENTRY: _openEHR-EHR-ADMIN_ENTRY.demographics.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
5+a|*Notifier* +
 `CLUSTER: _openEHR-EHR-CLUSTER.person.v0_`
5+a|*Structured name* +
 `CLUSTER: _openEHR-EHR-CLUSTER.structured_name.v0_`
|at0002 + 
 `first_name`| 0..*| DV_TEXT | First name
a|


The person's identifying first name(s) within the family group or by which they are uniquely socially identified.

_Annotations_


*comment*: Also known as a specific type of 'Given name'.
|at0005 + 
 `last_name`| 0..*| DV_TEXT | Last name
a|


The part of a name a person usually has in common with some other members of their family, as distinguished from their own given names.

_Annotations_


*comment*: Also known as 'Family name' or 'Surname'.
// Not supported rmType DV_IDENTIFIER
5+a|*Electronic communication* +
 `CLUSTER: _at0006_`
|at0007 + 
 `type`| 1..1| DV_CODED_TEXT | Type
a|
* at0008 -> Mobile (cellular) telephone 
* at0009 -> Telephone (excluding mobile telephone) 
* at0010 -> Email 
* at0011 -> Pager 
* _Other text allowed_


The type or medium for electronic communication.

_Annotations_


*comment*: The range of electronic communication mediums includes, but is not limited to use of : telephone, cellular phone, email, pager, fax, conferencing tool or social media.
// Not supported rmType ELEMENT
|at0012 + 
 `purpose`| 0..1| DV_CODED_TEXT | Purpose
a|
* at0013 -> Business use 
* _Other text allowed_


The purpose or use for the identified type of electronic communication.
|at0018 + 
 `comment`| 0..1| DV_TEXT | Comment
a|


Additional narrative about the electronic communication not captured in other fields.
5+a|*Organisation* +
 `CLUSTER: _openEHR-EHR-CLUSTER.organisation.v0_`
|at0001 + 
 `name`| 1..1| DV_TEXT | Name
a|


The unstructured name or label for the organisation.

_Annotations_


*comment*: For example: 'Royal Children's Hospital'; 'ABC District Nursing Service'; 'YNWA Oslo' or 'JB Smith Lawyers'.
// Not supported rmType DV_IDENTIFIER
5+a|*Address* +
 `CLUSTER: _openEHR-EHR-CLUSTER.address.v0_`
|at0009 + 
 `address`| 0..*| DV_TEXT | Address
a|


The unstructured address of the person or organisation.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0016 + 
 `health_region`| 0..*| DV_TEXT | Health Region
a|


The name of an internal political or geographic district or area within a state, territory or province containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible.
|at0016 + 
 `health_district_zone`| 0..*| DV_TEXT | Health District/Zone
a|


The name of an internal political or geographic district or area within a state, territory or province containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible.
|at0017 + 
 `parish`| 0..1| DV_TEXT | Parish
a|


The name of an internal political or geographic division of a country containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible. For example: Victoria; Alberta.
|at0019 + 
 `country`| 0..1| DV_TEXT | Country
a|


The name of the country containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible. For example: Australia; Canada
5+a|*Electronic communication* +
 `CLUSTER: _at0006_`
|at0007 + 
 `type`| 1..1| DV_CODED_TEXT | Type
a|
* at0008 -> Mobile (cellular) telephone 
* at0009 -> Telephone (excluding mobile telephone) 
* at0010 -> Email 
* at0011 -> Pager 
* at0020 -> Fax 
* _Other text allowed_


The type or medium for electronic communication.

_Annotations_


*comment*: The range of electronic communication mediums includes, but is not limited to use of: telephone, cellular phone, email, pager, fax, conferencing tool or social media.
// Not supported rmType ELEMENT
|====
=== Patient
===== `ADMIN_ENTRY: _openEHR-EHR-ADMIN_ENTRY.demographics.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
5+a|*Patient* +
 `CLUSTER: _openEHR-EHR-CLUSTER.person.v0_`
5+a|*Structured name* +
 `CLUSTER: _openEHR-EHR-CLUSTER.structured_name.v0_`
|at0002 + 
 `first_name`| 0..*| DV_TEXT | First name
a|


The person's identifying first name(s) within the family group or by which they are uniquely socially identified.

_Annotations_


*comment*: Also known as a specific type of 'Given name'.
|at0003 + 
 `middle_name`| 0..*| DV_TEXT | Middle name
a|


The person's identifying middle name(s) within the family group or by which they are uniquely socially identified.

_Annotations_


*comment*: Also known as a specific type of 'Given name'.
|at0004 + 
 `nickname`| 0..*| DV_TEXT | Nickname
a|


The person's identifying pet name or nickname(s) within the family group or by which they are uniquely socially identified.

_Annotations_


*comment*: Also known as a specific type of 'Given name'.
|at0005 + 
 `last_name`| 0..*| DV_TEXT | Last name
a|


The part of a name a person usually has in common with some other members of their family, as distinguished from their own given names.

_Annotations_


*comment*: Also known as 'Family name' or 'Surname'.
|at0006 + 
 `suffix`| 0..*| DV_TEXT | Suffix
a|


An additional term placed after all other name components, usually to differentiate the individual from a family member with identical name components.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible. For example: 'Junior (Jr)'; 'Senior (Sr)'; 'Second (II)'.
// Not supported rmType DV_IDENTIFIER
5+a|*Address* +
 `CLUSTER: _openEHR-EHR-CLUSTER.address.v0_`
|at0001 + 
 `type`| 0..1| DV_CODED_TEXT | Type
a|
* at0002 -> Physical 
* at0003 -> Postal 
* at0004 -> Both 


The type of address.

_Annotations_


*comment*: For example: physical or postal.
|at0005 + 
 `use`| 0..1| DV_CODED_TEXT | Use
a|
* at0006 -> Business 
* at0007 -> Residential 
* at0008 -> Temporary accommodation 
* _Other text allowed_


The primary purpose or use for the address.
|at0009 + 
 `type2`| 0..*| DV_TEXT | Type
a|


The type of address.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `physical`| 0..*| DV_TEXT | Physical
a|


A physical location that can be visited.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `postal`| 0..*| DV_TEXT | Postal
a|


Address used as a destination for mailing letters or parcels.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `both`| 0..*| DV_TEXT | Both
a|


Address of a physical location, also used as a destination for mail.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `type3`| 0..*| DV_TEXT | Type
a|


The type of address.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `physical2`| 0..*| DV_TEXT | Physical
a|


A physical location that can be visited.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `postal2`| 0..*| DV_TEXT | Postal
a|


Address used as a destination for mailing letters or parcels.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `both2`| 0..*| DV_TEXT | Both
a|


Address of a physical location, also used as a destination for mail.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0016 + 
 `community`| 0..*| DV_TEXT | Community
a|


The name of an internal political or geographic district or area within a state, territory or province containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible.
|at0017 + 
 `parish`| 0..1| DV_TEXT | Parish
a|


The name of an internal political or geographic division of a country containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible. For example: Victoria; Alberta.
|at0019 + 
 `country`| 0..1| DV_TEXT | Country
a|


The name of the country containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible. For example: Australia; Canada
5+a|*Electronic communication* +
 `CLUSTER: _at0006_`
|at0007 + 
 `type`| 1..1| DV_CODED_TEXT | Type
a|
* at0008 -> Mobile (cellular) telephone 
* at0009 -> Telephone (excluding mobile telephone) 
* at0010 -> Email 
* at0011 -> Pager 
* _Other text allowed_


The type or medium for electronic communication.

_Annotations_


*comment*: The range of electronic communication mediums includes, but is not limited to use of : telephone, cellular phone, email, pager, fax, conferencing tool or social media.
// Not supported rmType ELEMENT
|at0012 + 
 `purpose`| 0..1| DV_CODED_TEXT | Purpose
a|
* at0013 -> Business use 
* at0014 -> Personal use 
* at0015 -> Both business and personal use 
* _Other text allowed_


The purpose or use for the identified type of electronic communication.
5+a|*Birth details* +
 `CLUSTER: _openEHR-EHR-CLUSTER.birth_details.v0_`
|at0001 + 
 `date_time_of_birth`| 0..1| DV_DATE_TIME | Date/Time of birth
|
|at0002 + 
 `place_of_birth`| 0..1| DV_TEXT | Place of birth
a|



5+a|*Occupation record* +
 `CLUSTER: _openEHR-EHR-CLUSTER.occupation_record.v1_`
|at0005 + 
 `job_title_role`| 1..1| DV_TEXT | Job title/role
a|
* Health care worker
* Health laboratory worker
* Working with animals
* Student
* Cruise ship worker
* Airline worker
* EMT
* Prison worker
* Care home/Institution
* Agricultural worker
* Hotel worker
* Unemployed


The main job title or the role of the individual.

_Annotations_


*comment*: For example: Chief Executive Officer; Carer; or Student. Each of these job titles or roles may be comprised of multiple duties.
5+a|*Organisation* +
 `CLUSTER: _openEHR-EHR-CLUSTER.organisation.v0_`
|at0001 + 
 `name`| 1..1| DV_TEXT | Name
a|


The unstructured name or label for the organisation.

_Annotations_


*comment*: For example: 'Royal Children's Hospital'; 'ABC District Nursing Service'; 'YNWA Oslo' or 'JB Smith Lawyers'.
5+a|*Address* +
 `CLUSTER: _openEHR-EHR-CLUSTER.address.v0_`
|at0001 + 
 `type`| 0..1| DV_CODED_TEXT | Type
a|
* at0002 -> Physical 


The type of address.

_Annotations_


*comment*: For example: physical or postal.
|at0005 + 
 `use`| 0..1| DV_CODED_TEXT | Use
a|
* at0006 -> Business 
* at0008 -> Temporary accommodation 
* _Other text allowed_


The primary purpose or use for the address.
|at0009 + 
 `type2`| 0..*| DV_TEXT | Type
a|


The type of address.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `physical`| 0..*| DV_TEXT | Physical
a|


A physical location that can be visited.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `postal`| 0..*| DV_TEXT | Postal
a|


Address used as a destination for mailing letters or parcels.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `both`| 0..*| DV_TEXT | Both
a|


Address of a physical location, also used as a destination for mail.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `type3`| 0..*| DV_TEXT | Type
a|


The type of address.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `physical2`| 0..*| DV_TEXT | Physical
a|


A physical location that can be visited.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `postal2`| 0..*| DV_TEXT | Postal
a|


Address used as a destination for mailing letters or parcels.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0009 + 
 `both2`| 0..*| DV_TEXT | Both
a|


Address of a physical location, also used as a destination for mail.

_Annotations_


*comment*: This address line represents a low level of geographical/physical description of a location that, used in conjunction with the other high-level address components i.e. ‘Suburb/Town/Locality’, ‘Postcode’, and ‘State/Territory/Province’, forms a complete geographical/physical address. This data element can be used to represent a landmark, such as "The second house north of the general store" or "At the corner of Smith & Brown Streets.
The content of this data element may be derived from a concatenation of one or more components from CLUSTER.structured_address.
Multiple occurrences allow for as many 'Address' lines, as required. For example: 4 address lines represented as
Apartment 7A,
52 Davis Street,
Carlton North,
Victoria, AUSTRALIA 3042.
|at0016 + 
 `community`| 0..*| DV_TEXT | Community
a|


The name of an internal political or geographic district or area within a state, territory or province containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible.
|at0017 + 
 `parish`| 0..1| DV_TEXT | Parish
a|


The name of an internal political or geographic division of a country containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible. For example: Victoria; Alberta.
|at0019 + 
 `country`| 0..1| DV_TEXT | Country
a|


The name of the country containing the address.

_Annotations_


*comment*: Coding with an external terminology is preferred, where possible. For example: Australia; Canada
5+a|*Electronic communication* +
 `CLUSTER: _at0006_`
|at0007 + 
 `type`| 1..1| DV_CODED_TEXT | Type
a|
* at0008 -> Mobile (cellular) telephone 
* at0009 -> Telephone (excluding mobile telephone) 
* at0010 -> Email 
* at0011 -> Pager 
* at0020 -> Fax 
* _Other text allowed_


The type or medium for electronic communication.

_Annotations_


*comment*: The range of electronic communication mediums includes, but is not limited to use of: telephone, cellular phone, email, pager, fax, conferencing tool or social media.
// Not supported rmType ELEMENT
|====
=== Emergency Contact
===== `ADMIN_ENTRY: _openEHR-EHR-ADMIN_ENTRY.demographics.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
5+a|*Person* +
 `CLUSTER: _openEHR-EHR-CLUSTER.person.v0_`
5+a|*Structured name* +
 `CLUSTER: _openEHR-EHR-CLUSTER.structured_name.v0_`
|at0002 + 
 `first_name`| 0..*| DV_TEXT | First name
a|


The person's identifying first name(s) within the family group or by which they are uniquely socially identified.

_Annotations_


*comment*: Also known as a specific type of 'Given name'.
|at0005 + 
 `last_name`| 0..*| DV_TEXT | Last name
a|


The part of a name a person usually has in common with some other members of their family, as distinguished from their own given names.

_Annotations_


*comment*: Also known as 'Family name' or 'Surname'.
// Not supported rmType DV_IDENTIFIER
5+a|*Electronic communication* +
 `CLUSTER: _at0006_`
|at0007 + 
 `type`| 1..1| DV_CODED_TEXT | Type
a|
* at0008 -> Mobile (cellular) telephone 
* at0009 -> Telephone (excluding mobile telephone) 
* at0010 -> Email 
* at0011 -> Pager 
* _Other text allowed_


The type or medium for electronic communication.

_Annotations_


*comment*: The range of electronic communication mediums includes, but is not limited to use of : telephone, cellular phone, email, pager, fax, conferencing tool or social media.
// Not supported rmType ELEMENT
|at0012 + 
 `purpose`| 0..1| DV_CODED_TEXT | Purpose
a|
* at0013 -> Business use 
* at0014 -> Personal use 
* at0015 -> Both business and personal use 
* _Other text allowed_


The purpose or use for the identified type of electronic communication.
|====
== Class 1 Reporting
=== Admission details
===== `ADMIN_ENTRY: _openEHR-EHR-ADMIN_ENTRY.admission.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0002 + 
 `patient_class`| 1..1| DV_CODED_TEXT | Patient class
a|
* at0003 -> Inpatient/overnight patient 
* at0005 -> Outpatient 
* at0006 -> Emergency patient 
* at0011 -> Unknown 


Intended mode of treatement.
5+a|*Assigned patient location* +
 `CLUSTER: _at0073_`
|at0077 + 
 `ward`| 0..1| DV_TEXT | Ward
a|
* Male
* Female


*
|at0079 + 
 `bed`| 0..1| DV_TEXT | Bed
a|


*
|at0071 + 
 `admit_date_time`| 1..1| DV_DATE_TIME | Admit date/time
|
|====
=== Syndromic questionnaire
===== `OBSERVATION: _openEHR-EHR-OBSERVATION.symptom_sign_screening.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `time`| 1..1| DV_DATE_TIME | Time
|
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0028 + 
 `are_there_any_symptoms_or_signs`| 0..1| DV_CODED_TEXT | Are there any symptoms or signs
a|
* at0031 -> Yes 
* at0032 -> No 
* at0033 -> Unknown 


Presence of any relevant symptoms or signs.
|at0029 + 
 `onset_of_1st_symptoms_or_signs`| 0..1| DV_DATE_TIME | Onset of 1st symptoms or signs
|

_Annotations_


*comment*: Partial dates are allowed.
5+a|*Specific symptom/sign* +
 `CLUSTER: _at0022_`
|at0004 + 
 `symptom_or_sign_name`| 1..*| DV_TEXT | Symptom or sign name
a|
* Cough
* Sore Throat
* SOB
* Difficulty Breathing/Wheezing
* Nausea/Vomiting
* Headache
* Myalgia
* Dyspnea/Tachypnea
* Abnormal Lung Auscultation
* Abnormal Lung/Xray Findings
* Seizure
* Fever over 38 C
* Fever
* Weakness
* Ageusia (Loss of Taste)
* Runny Nose
* Anosmia (Loss of Smell)
* Diarrhoea
* Joint Pain
* Vomiting
* Nasal Congestion/Stuffy Nose
* Chest Pain
* Loss of Appetite
* Fatigue
* Chills
* Sneezing
* Back Pain
* Malaise
* Post-nasal Drip
* Chest Tightness
* Abdominal Pain
* Eye Pain
* Conjunctivitis
* Tachypnoea/Abnormal Breathing
* Dizziness
* Haemoptysis
* _Other text allowed_


Name of the symptom or sign being screened.
|at0037 + 
 `duration`| 0..1| DV_DURATION | Duration
|
|====
=== Additional Symptoms
===== `OBSERVATION: _openEHR-EHR-OBSERVATION.symptom_sign_screening.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `time`| 1..1| DV_DATE_TIME | Time
|
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0028 + 
 `are_there_any_symptoms_or_signs`| 0..1| DV_CODED_TEXT | Are there any symptoms or signs
a|
* at0031 -> Yes 
* at0032 -> No 
* at0033 -> Unknown 


Presence of any relevant symptoms or signs.
|at0029 + 
 `onset_of_1st_symptoms_or_signs`| 0..1| DV_DATE_TIME | Onset of 1st symptoms or signs
|

_Annotations_


*comment*: Partial dates are allowed.
|at0036 + 
 `description`| 0..1| DV_TEXT | Description
a|


Narrative description about all symptoms or signs.
5+a|*Specific symptom/sign* +
 `CLUSTER: _at0022_`
|at0004 + 
 `symptom_or_sign_name`| 1..*| DV_TEXT | Symptom or sign name
a|
* Cough
* Sore Throat
* SOB
* Difficulty Breathing/Wheezing
* Nausea/Vomiting
* Headache
* Myalgia
* Dyspnea/Tachypnea
* Abnormal Lung Auscultation
* Abnormal Lung/Xray Findings
* Seizure
* Fever over 38 C
* Fever
* Weakness
* Ageusia (Loss of Taste)
* Runny Nose
* Anosmia (Loss of Smell)
* Diarrhoea
* Joint Pain
* Vomiting
* Nasal Congestion/Stuffy Nose
* Chest Pain
* Loss of Appetite
* Fatigue
* Chills
* Sneezing
* Back Pain
* Malaise
* Post-nasal Drip
* Chest Tightness
* Abdominal Pain
* Eye Pain
* Conjunctivitis
* Tachypnoea/Abnormal Breathing
* Dizziness
* Haemoptysis
* _Other text allowed_


Name of the symptom or sign being screened.
|at0037 + 
 `duration`| 0..1| DV_DURATION | Duration
|
|====
=== Health risk assessment
===== `EVALUATION: _openEHR-EHR-EVALUATION.health_risk.v1_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0002 + 
 `health_risk`| 1..1| DV_TEXT | Health risk
a|


Identification of the potential future disease, condition or health issue for which the risk is being assessed, by name.

_Annotations_


*comment*: Coding of 'Health risk' with a terminology is preferred, where possible. Free text should be used only if there is no appropriate terminology available. For example: risk of cardiovascular disease, with risk factors of hypertension and hypercholesterolaemia.
5+a|*Risk factors* +
 `CLUSTER: _at0016_`
|at0013 + 
 `risk_factor`| 1..*| DV_TEXT | Risk factor
a|
* DM
* SCD
* Heart Disease
* Lung Disease
* Asthma
* Neurological Disease
* Liver Disease
* Renal Disease
* Immunocompromised due to disease or treatment
* HIV/AIDS
* Malignancy
* Pregnancy


Identification of the risk factor, by name.

_Annotations_


*comment*: For example: hypertension and hypercholesterolaemia, which may be used as part of the overall assessment for cardiovascular disease; or a genetic marker. Coding of 
'Risk factor' with a terminology, where possible.
|at0014 + 
 `description`| 0..1| DV_TEXT | Description
a|


Narrative description about the risk factor.
|at0029 + 
 `date_identified`| 0..1| DV_DATE_TIME | Date identified
|
|====
== Case investigation
=== Problem/Diagnosis
===== `EVALUATION: _openEHR-EHR-EVALUATION.problem_diagnosis.v1_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0002 + 
 `problem_diagnosis_name`| 1..1| DV_TEXT | Problem/Diagnosis name
a|
* SARS-CoV-2


Identification of the problem or diagnosis, by name.

_Annotations_


*comment*: Coding of the name of the problem or diagnosis with a terminology is preferred, where possible.
|====
=== Travel event
===== `OBSERVATION: _openEHR-EHR-OBSERVATION.travel_event.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
// Not supported rmType INTERVAL_EVENT
|====
=== Exposure screening questionnaire
===== `OBSERVATION: _openEHR-EHR-OBSERVATION.exposure_assessment.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `time`| 1..1| DV_DATE_TIME | Time
|
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0043 + 
 `agent`| 1..1| DV_TEXT | Agent
a|
* Covid-19


The name of the chemical, physical or biological agent to which an individual may have been exposed.

_Annotations_


*comment*: Coding of 'Agent' with a terminology is preferred, where possible. Free text should be used only if there is no appropriate terminology available. For example: 2019-nCoV; or HIV.
|at0057 + 
 `any_exposure`| 0..1| DV_CODED_TEXT | Any exposure?
a|
* at0058 -> Exposed 
* at0059 -> Not exposed 
* at0060 -> Unknown 
* _Other text allowed_


Presence of any relevant exposure.
5+a|*Specific exposure* +
 `CLUSTER: _at0044_`
|at0045 + 
 `exposure_situation`| 1..1| DV_TEXT | Exposure situation
a|
* Close Contact with respiratory symptoms
* Confirmed Case
* Probable Case
* Visited a Health Facility within 14 days
* Animal Contact
* Travel abroad within 14 days
* Contact with traveler in past 14 days
* Other


The circumstance of possible exposure.

_Annotations_


*comment*: For example: Travel to an 'at risk' location; exposure to infected body fluids; or worked as a dental technician. Coding of 'Exposure situation' with a terminology is preferred, where possible.
// Not supported rmType ELEMENT
|at0055 + 
 `comment`| 0..1| DV_TEXT | Comment
a|


Additional narrative about the specific exposure event, not captured in other fields.
|====
=== Potential Exposure Contact
===== `ADMIN_ENTRY: _openEHR-EHR-ADMIN_ENTRY.care_team.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
5+a|*Contact details* +
 `CLUSTER: _openEHR-EHR-CLUSTER.care_team.v0_`
5+a|*Contact* +
 `CLUSTER: _at0021_`
5+a|*Contact details* +
 `CLUSTER: _openEHR-EHR-CLUSTER.contact_cc.v0_`
5+a|*Name of Contact* +
 `CLUSTER: _openEHR-EHR-CLUSTER.person_name.v1_`
5+a|*Structured name* +
 `CLUSTER: _at0002_`
|at0003 + 
 `first_name`| 1..*| DV_TEXT | First name
a|


Given / personal / first name.
|at0005 + 
 `last_name`| 1..1| DV_TEXT | Last name
a|


Family name or Surname.
5+a|*Telecom of Contact* +
 `CLUSTER: _openEHR-EHR-CLUSTER.telecom_cc.v0_`
|at0001 + 
 `type`| 0..1| DV_CODED_TEXT | Type
a|
* at0012 -> Phone 
* at0013 -> Fax 
* at0014 -> Email 
* at0015 -> URL 
* at0016 -> Pager 
* at0017 -> SMS 
* at0018 -> Other 


Telecommunications form for contact point - what communications system is required to make use of the contact.
|at0002 + 
 `details`| 0..1| DV_TEXT | Details
a|


The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).
5+a|*Address* +
 `CLUSTER: _openEHR-EHR-CLUSTER.address_cc.v1_`
|at0001 + 
 `use`| 0..1| DV_CODED_TEXT | Use
a|
* Current (local_terms: 01)
* Temporary (local_terms: 02)
* Other (local_terms: 03)


The purpose of the address.
|at0015 + 
 `country`| 0..1| DV_TEXT | Country
a|
* Jamaica
* Canada
* United Kingdom
* United States
* _Other text allowed_


Country - a nation as commonly understood or generally accepted.
|at0013 + 
 `parish`| 0..1| DV_TEXT | Parish
a|
* Kingston
* Saint Andrew
* Portland
* Saint Thomas
* Saint Catherine
* Saint Mary
* Saint Ann
* Manchester
* Clarendon
* Hanover
* Westmoreland
* Saint James
* Trelawny
* Saint Elizabeth
* _Other text allowed_


The name of the administrative area (county).
|at0010 + 
 `full_address`| 0..1| DV_TEXT | Full address
a|


A full text representation of the address.
|at0011 + 
 `community`| 0..*| DV_TEXT | Community
a|


This component contains the house number, apartment number, street name, street direction, P.O. Box number, delivery hints, and similar address information.
|at0021 + 
 `additional_description`| 0..1| DV_TEXT | Additional Description
a|



|====
=== Body temperature
===== `OBSERVATION: _openEHR-EHR-OBSERVATION.body_temperature.v1_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `time`| 1..1| DV_DATE_TIME | Time
|
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0004 + 
 `temperature`| 1..1| DV_QUANTITY | Temperature
|
|====