= EA - About Me.v0


== *About me*


=== `COMPOSITION: _openEHR-EHR-COMPOSITION.anticipatory_care_information.v0_`


===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0001 + 
 `coded_text`| 1..1| DV_CODED_TEXT | Coded text
a|
* undefined (openehr: 433)


*
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `territory`| 1..1| CODE_PHRASE | territory
|
|RM: + 
 `composer`| 1..1| PARTY_PROXY | composer
|
|====
=== context
===== `EVENT_CONTEXT: _at0002_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `start_time`| 1..1| DV_DATE_TIME | Start_time
|
|RM: + 
 `setting`| 1..1| DV_CODED_TEXT | Setting
a|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
5+a|*XDS Metadata* +
 `CLUSTER: _openEHR-EHR-CLUSTER.xds_metadata.v0_`
===== Annotations]
[options="header", cols="5,30"]
|Key|Value|


| comment | for example:  Pulmonary History and Physical, Discharge Summary, Ultrasound Report.
These codes are specific to an XDS Affinity Domain.|
|====
|at0003 + 
 `document_type`| 0..1| DV_TEXT | Document type
a|


The code specifying the precise type of document from the user perspective. Normally selected from a valueset provided by the local IHE-XDS Affinity Domain or national standard.
|====
=== About me
===== `EVALUATION: _openEHR-EHR-EVALUATION.about_me.v0_`
===== RM attributes
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|RM: + 
 `language`| 1..1| CODE_PHRASE | language
|
|RM: + 
 `encoding`| 1..1| CODE_PHRASE | encoding
|
|RM: + 
 `subject`| 1..1| PARTY_PROXY | subject
|
|====
[options="header", cols="5,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name | Description
|at0002 + 
 `what_is_most_important_to_me`| 0..1| DV_TEXT | What is most important to me
a|



|at0002 + 
 `people_who_are_important_to_me`| 0..1| DV_TEXT | People who are important to me
a|



|at0002 + 
 `how_i_communicate_and_how_to_communicate_with_me`| 0..1| DV_TEXT | How I communicate and how to communicate with me
a|



|at0002 + 
 `please_do_and_please_dont`| 0..1| DV_TEXT | Please do and please dont
a|



|at0002 + 
 `my_wellness`| 0..1| DV_TEXT | My wellness
a|



|at0002 + 
 `how_and_when_to_support_me`| 0..1| DV_TEXT | How and when to support me
a|



|at0002 + 
 `also_worth_knowing_about_me`| 0..1| DV_TEXT | Also worth knowing about me
a|



5+a|*About me attachment* +
 `CLUSTER: _openEHR-EHR-CLUSTER.multimedia_source.v0_`
|at0002 + 
 `resource_name`| 0..1| DV_TEXT | Resource name
a|


Name or title of the multimedia resource.
|at0005 + 
 `description`| 0..1| DV_TEXT | Description
a|


Narrative description about the resource.
// Not supported rmType DV_MULTIMEDIA
|at0004 + 
 `created`| 0..1| DV_DATE_TIME | Created
|
|====